server:
  port: 8010

spring:
  application:
    name: springcloud-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yoong_rehearsal?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #zipkin，分布式链路跟踪
  zipkin:
    base-url: http://127.0.0.1:8070/
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true




