server:
  port: 8060

spring:
  application:
    name: springcloud-zuul
  #zipkin，分布式链路跟踪
#  zipkin:
#    base-url: http://127.0.0.1:8070/
#  sleuth:
#    sampler:
#      percentage: 1.0


#springcloud(十)：服务网关zuul
#https://www.cnblogs.com/ityouknow/p/6944096.html
#若要禁用Zuul，注释启动类的@EnableZuulProxy注解即可


#一、简单使用(不需要Eureka依赖、Eureka配置)
#配置 /user/**、http://localhost:8010/user/，匹配/user/**，重定向到http://localhost:8010/user/**，
#   访问 http://127.0.0.1:8060/user/get?userId=6 -> http://localhost:8010/user/get?userId=6
#   访问 http://127.0.0.1:8060/user/getTime -> http://localhost:8010/user/getTime
#   访问 http://127.0.0.1:8060/getTime2 -> http://localhost:8010/user/getTime2，Whitelabel Error Page(type=Not Found, status=404)

#配置 /user/**、http://localhost:8010/，匹配/user/**，重定向到http://localhost:8010/**，
#   访问 http://127.0.0.1:8060/user/user/get?userId=6 -> http://localhost:8010/user/get?userId=6
#   访问 http://127.0.0.1:8060/user/user/getTime -> http://localhost:8010/user/getTime
#   访问 http://127.0.0.1:8060/user/getTime2 -> http://localhost:8010/user/getTime2

#配置 /myZuul/**、http://localhost:8010/，匹配/myZuul/**，重定向到http://localhost:8010/**，
#   访问 http://127.0.0.1:8060/myZuul/getTime2 -> http://localhost:8010/getTime2
#   访问 http://127.0.0.1:8060/myZuul/user/getTime -> http://localhost:8010/user/getTime

#配置 /getTime2、http://localhost:8010/，匹配/getTime2，重定向到http://localhost:8010/**，
#   访问 http://127.0.0.1:8060/getTime2 -> http://localhost:8010/getTime2
#zuul:
#  routes:
#    provider:
#      path: /user/**
#      url: http://localhost:8010/user
#    provider2:
#     path: /myZuul/**
#     url: http://localhost:8010/
#    provider3:
#     path: /getTime2
#     url: http://localhost:8010/


#二、服务化(需要Eureka依赖、Eureka配置)
#若添加了netflix-eureka-client依赖，不配置eureka，正常启动，但定时心跳时会报错：Cannot execute request on any known server\There was a problem with the instance info replicator
#将**的url映射到springcloud-provider
#配置/user/**，访问 http://localhost:8060/user/user/getTime -> http://localhost:8010/user/getTime
#配置/user/**，访问 http://localhost:8060/user/getTime2 -> http://localhost:8010/getTime2
#配置/user/**，访问 http://127.0.0.1:8060/myZuul/user/getTime2，Whitelabel Error Page(type=Not Found, status=404)
#配置/myZuul/user/**，访问 http://127.0.0.1:8060/myZuul/user/getTime2 -> http://localhost:8010/getTime2
#zuul:
#  routes:
#    provider:
#      path: /myZuul/user/**
#      serviceId: springcloud-provider


#三、网关的默认路由规则
#Zuul的路由规则：http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**，会被转发到serviceId对应的微服务
#访问 http://localhost:8060/springcloud-provider/user/getTime -> http://localhost:8010/user/getTime
#访问 http://localhost:8060/springcloud-provider/getTime2 -> http://localhost:8010/getTime2
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/

