server:
  port: 8087

spring:
  application:
    name: hystrix-dashboard-turbine


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://peer1:9761/eureka/,http://peer2:9762/eureka/,http://peer3:9763/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
turbine:
  app-config:


