server:
  port: 8030

spring:
  application:
    name: hystrix-dashboard-turbine

turbine:
  app-config: springcloud-consumer,springcloud-consumer1  # 配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator:
    cluster-config: default # 指定聚合哪些集群，多个使用","分割，默认为default。
  cluster-name-expression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    prefer-ip-address: true




