server:
  port: 8084

spring:
  application:
    name: springcloud-consumer1
  datasource:
    url:jdbc: mysql://127.0.0.1:3306/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:9761/eureka/,http://peer2:9762/eureka/,http://peer3:9763/eureka/
#    register-with-eureka: false
#    fetch-registry: false

feign:
  hystrix:
    enabled: true



