server:
  port: 8020

spring:
  application:
    name: springcloud-consumer
  datasource:
    url:jdbc: mysql://127.0.0.1:3306/yoong_rehearsal?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
#    register-with-eureka: false
#    fetch-registry: false

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 900000000
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000


