server:
  port: 8040

# 访问 http://localhost:8040/yoong/test，测试server端是否可以读取到github上面的配置信息
# 访问 http://localhost:8040/yoong-test.properties，直接查看配置文件中的配置信息
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiongc169/20181205-SpringCloud
          search-paths: config-repo
          username:
          password:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: user
#    password: 123456

#权限配置
management:
  security:
    enabled: false

#注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/