server:
  port: 8041

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiongc169/20181205-SpringCloud
          search-paths: config-repo
          username:
          password:

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/