server:
  port: 8050

#spring配置
spring:
  application:
    name: springcloud-config-client
  cloud:
    config:
      name: yoong
      profile: dev
      uri: http://127.0.0.1:8040
      label: master
      discovery:
        enabled: true
        service-id: springcloud-config-server
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: 123456

#权限配置
management:
  security:
    enabled: false

#注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/ #http://127.0.0.1:8761/eureka/,http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/

