server:
  port: 8110

#http://127.0.0.1:8110/SPRINGCLOUD-PROVIDER/user/getTime
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: neo_route
        uri: http://www.baidu.com
        predicates:
         Path=/gateway/getTime


#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: baidu
#        uri: http://127.0.0.1:8010/
#        predicates:
#          - Path=/gateway/getTime
#        filters:


#  cloud:
#    gateway:
#      routes:
#       -id: baidu
#       uri: http://www.baidu.com
#       predicates:
#        -Path: /getTime/**
