server:
  port: 8110


#http://127.0.0.1:8110/gateway/getTime
#默认路由规则：http://127.0.0.1:8110/SPRINGCLOUD-PROVIDER/user/getTime

#访问 http://127.0.0.1:8110/getTime, 跳转到 http://127.0.0.1:8010/getTime
#访问 http://127.0.0.1:8110/user/getTime, 跳转不到 http://127.0.0.1:8010/user/getTime
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: local
        uri: http://127.0.0.1:8010/
        predicates:
        - Path=/getTime


#访问 http://127.0.0.1:8110/user/getTime, 跳转到 http://127.0.0.1:8010/user/getTime
#spring:
#  application:
#    name: springcloud-gateway
#  cloud:
#    gateway:
#      routes:
#      - id: local
#        uri: http://127.0.0.1:8010/
#        predicates:
#        - Path=/user/getTime


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/

