server:
  port: 8070

spring:
  application:
    name: springcloud-sleuth

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

