#peer1服务中心的配置，将serviceUrl指向peer2
#java -jar springcloud-eureka.jar --spring.profiles.active=peer1
server:
  port: 8000

spring:
  application:
    name: springcloud-eureka-ha

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/

