server:
  port: 8761

spring:
  application:
    name: sc-eureka

eureka:
  instance:
    hostname: peer1
    appname: sc-eureka-app
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8760/eureka/
