#peer2服务中心的配置，将serviceUrl指向peer1
#java -jar springcloud-eureka.jar --spring.profiles.active=peer2
server:
  port: 8001

spring:
  application:
    name: springcloud-eureka-ha

eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/

