spring:
  application:
    name: springcloud-eureka-ha

---

spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer2:8762/eureka/

---

spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  clienzt:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka/

