server:
  port: 8761

spring:
  application:
    name: springcloud-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

