#peer1服务中心的配置，将serviceUrl指向peer2
#java -jar springcloud-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
spring:
  application:
    name: springcloud-eureka-ha

server:
  port: 9761

eureka:
  instance:
    hostname: peer1
  client:
#    register-with-eureka: false
#    fetch-registry: false
#    healthcheck:
#      enabled: true
    service-url:
      defaultZone: http://peer2:9762/eureka/,http://peer3:9763/eureka/

