server:
  port: 8761 # ${random.int(8000,8100)}，随机端口

spring:
  application:
    name: springcloud-eureka

eureka:
  instance:
    hostname: peer1
    appname: springcloud-eureka-app
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer2:8761/eureka/

