server:
  port: 8120

spring:
  application:
    name: springcloud-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

