server:
  port: 8090

spring:
  application:
    name: springcloud-consul-provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: springcloud-consul-service
